### PR TITLE
feat: import + export scripts with extraction

### PR DESCRIPTION
**Pull request by meesvandongen**
- new -x --extract option for import
- new -A --all-separate option for export
- new -w --watch option for export

### CODE REVIEW

**Comment by vscheuber** [comment]
@meesvandongen I hope to be able to merge this soon. I have been working on some substantial restructuring over the holidays and are still wrapping that up. Script API and OPS layer are part of that restructuring, so I might ask you to re-submit the PR depending on how messy things get when I try to merge.

**Comment by vscheuber** [comment]
@meesvandongen I finished restructuring and refactoring the script api and ops layers in both frodo-lib and frodo-cli and there is no way for me to merge your great work as the changes are too big. I could manually re-code what you did but I don't want to put my name under your great contribution. If you feel up to it, please checkout the latest code base for both lib and cli and re-implement your new feature. If you don't want to do that, say the word and I will do it but it won't have your name to it.

The main change is that we properly split lib from cli for everything script. We have been doing this little by little for every piece and it is an ongoing process. I believe that with what we have today, your whole contribution would live in frodo-cli.

**Comment by meesvandongen** [comment]
@vscheuber I have updated the code somewhat to reflect the new architecture. There is something I would propose should be handled differently: currently the `lib` package is responsible for handling the progress indicator, I think this too should be moved to `cli`. Also, the progress indicator kept the node process open for some reason when calling multiple import scripts functions at once. I have not investigated this further however.

**Comment by meesvandongen** [comment]
@vscheuber I have tested the changes for a JS file import, and they seem to work. Imo the PR is ready to merge, but of course feel free to change anything or request changes from me.

**Comment by vscheuber** [comment]
HI @meesvandongen , may I ask you to squash your commits in this PR? All the December commits don’t really apply and they are giving me merge issues. After a rebase against the latest version (there should be no changes affecting scripts) and squashing the commits, I’ll merge asap.

**Comment by vscheuber** [comment]
I haven’t fully grasped the functionality you added. Some of the flags are on opposite commands I would expect them to be on. Maybe a demo would be helpful for me to understand your thinking?

For example I would expect the `-x` option to be on export, not import, or to be renamed to `—merge vs `—extracts. The watch open also I feel like should be available on import, not on export, so that I can develop code in my favorite IDE and have frodo watch the extracted script files and merge them on change and push them to AM if they have no errors.

I think I may just be misunderstanding what the intention of your feature is vs what I had in mind.

**Comment by meesvandongen** [comment]
The feature works exactly as you describe; -x is on export, -w is on import. I am open to other names, of course (including the file name, which is now .extract.js).
I will look into recording a demo tomorrow.

On Monday 16 January 2023 18:42:02 (+01:00), Volker Scheuber wrote:



I haven’t fully grasped the functionality you added. Some of the flags are on opposite commands I would expect them to be on. Maybe a demo would be helpful for me to understand your thinking?

For example I would expect the -x option to be on export, not import, or to be renamed to —merge vs —extracts. The watch open also I feel like should be available on import, not on export, so that I can develop code in my favorite IDE and have frodo watch the extracted script files and merge them on change and push them to AM if they have no errors.

I think I may just be misunderstanding what the intention of your feature is vs what I had in mind.

**Comment by vscheuber** [comment]
@meesvandongen ok, great!! Maybe it’s only the commit comment that is wrong, then, and confessed me:
```
new -x --extract option for import
new -A --all-separate option for export
new -w --watch option for export
```

**Comment by meesvandongen** [comment]
@vscheuber that is confusing; I wasn't paying attention at that time I suppose.

Here is the link to the demo: https://youtu.be/yGPnk7gR1dY

**Comment by vscheuber** [comment]
@meesvandongen YOU DA MAN! Super cool demo! This looks great!!

I would like to suggest 2 changes:

- squash commits
- use `scriptname.js` or `scriptname.groovy` (without the `extract`)
- use a full URL instead of just the file name to link from the export to the extracted script. That would allow us to store the script anywhere, as long as the URL leads to the code. Could be on an external server, maybe even GitHub, etc.
- use slugify to create a safe filename from the script name (see `getTypedFilename` in `ExportImportUtils`) if you are not already doing that.

Future:

- think about how we can leverage the extract command to save the scripts to different locations (other directories, on a server, etc.) and then use the URL to link to it.

**Comment by meesvandongen** [comment]
Those are 4 changes!

1/2: will do. 

3: Currently it works 2 ways for local files; if you update the json it will look for the file in the same folder. What we could do is make it a relative file name using `path.relative`; if we want to support multiple protocols to get the files, we should consider if we want to prefix the `file` type with `file://` or not. I suppose we could get away with not doing that however, if we consider the `file` protocol the default. Then future protocols could use `something://etc` and there would still be no breaking changes.

4: It currently uses the same name as the .json, which is already slugified.

**Comment by meesvandongen** [comment]
Although, what occurred to me is that we do change detection for both the .js and the .json file. We match the files by file name of the changed file. So, the file string inside the json is not used at all; and it would involve quite some complexity to add files outside of the initial folder.

For example, consider that we add `../file.js`, to some `./file.json`. We would have to look inside the json file for the link to the js file, and setup a listener for file changes using chokidar for that file. We would also need to keep (in memory) a list of file links, so we can match them up if we detect a change event the .js file. And we would have to handle the lifecycle of the file, i.e. rename, delete, create, and start/stop listening to file change events accordingly.

**Comment by vscheuber** [comment]
That makes sense, @meesvandongen. I think the --watch option requires certain ground rules to be followed. I was thinking let's get to the URL format just so that we don't have to write a converter later on and can handle any type of protocol. Of course the choice of protocol may limit the ability to use --watch. I'm fine to merge whenever you are ready. We can respond to community feedback as we go.

**Comment by meesvandongen** [comment]
closed in favor of #188

**Pull request closed without merging**
